export const TOPIC = {
  SET_PLAYER_OPTION: 'SET_PLAYER_OPTION',
  UPDATE_GAMEBOARD: 'UPDATE_GAMEBOARD',
  SHOW_GAMEBOARD: 'SHOW_GAMEBOARD',
  HIDE_GAMEBOARD: 'HIDE_GAMEBOARD',
  PASS_DEVICE: 'PASS_DEVICE',
  PING_SHOW_GAMEBOARD: 'PING_SHOW_GAMEBOARD',
  PING_HIDE_GAMEBOARD: 'PING_HIDE_GAMEBOARD',
  PING_SETUP_PLAYERS: 'PING_SETUP_PLAYERS',
  SETUP_SHIPS: 'SETUP_SHIPS',
  START_GAME: 'START_GAME'
}
